image: nqoki709/monolis_build:latest

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - api_failure
      - stuck_or_timeout_failure
      - unknown_failure

stages:
  - lib_build
  - test
  - doxy_build
  - deploy

build_monolis:
  stage: lib_build
  script:
    - ./install_lib.sh
    - make all FLAGS=DEBUG
  artifacts:
    expire_in: 1 day
    paths:
      - bin
      - include
      - lib
      - src_test/monolis_test
      - wrapper_test/monolis_c_test
    exclude:
      - "**/*.o"

test_monolis:
  stage: test
  script:
    - cd src_test
    - ./run.CI.sh
    - cd ../wrapper_test
    - ./run.CI.sh
  dependencies:
    - build_monolis

doxygen_monolis:
  stage: doxy_build
  script:
    - doxygen -v
    - cd manual/fortran
    - doxygen
    - cd ../c
    - doxygen
  artifacts:
    expire_in: 1 day
    paths:
      - manual

pages:
  stage: deploy
  dependencies:
    - doxygen_monolis
  script:
    - mkdir public
    - mv manual/fortran/html public/fortran
    - mv manual/c/html public/c
  artifacts:
    paths:
      - public
